export const initOption = {
  value: 'init',
  text: 'Selecciona una opción',
  disabled: true,
}

export function setPlantel(programa, arrPlanteles) {
  let planteles = []
  switch (programa) {
    case 'Administracion':
      planteles = [
        'Centro',
        'Chalco',
        'CD. Azteca',
        'Coacalco',
        'Cuautitlán',
        'Ermita',
        'Iztapalapa',
        'Norte',
        'León',
        'Oriente',
        'San Ángel',
        'Sur I',
        'Tláhuac',
        'Tlalnepantla',
        'Toluca',
        'Toreo',
        'Vía Morelos',
        'Chapultepec',
        'IESCA',
      ]
      break
    case 'Administracion de Tecnologias de la Informacion':
      planteles = [
        'Centro',
        'Ciudad Azteca',
        'Coacalco',
        'Cuautitlán',
        'Ermita',
        'Norte',
        'Oriente',
        'San Ángel',
        'Sur I',
        'Tláhuac',
        'Tlalnepantla',
        'Toluca',
        'Toreo',
        'Vía Morelos',
      ]
      break
    case 'Arquitectura':
      planteles = [
        'León',
        'San Ángel',
        'Sur I',
        'Tlalnepantla',
        'Toluca',
        'Vía Morelos',
        'Norte',
      ]
      break
    case 'Ciencias de la Comunicaci_n':
      planteles = ['Tlalpan']
      break
    case 'Comercio Internacional':
      planteles = [
        'Centro',
        'Coacalco',
        'Tlalnepantla',
        'Tlapan',
        'Vía Morelos',
      ]
      break
    case 'Contadur_':
      planteles = [
        'Centro',
        'Chalco',
        'CD. Azteca',
        'Cuautitlán',
        'Iztapalapa',
        'Norte',
        'León',
        'Oriente',
        'San Ángel',
        'Sur I',
        'Tláhuac',
        'Tlalnepantla',
        'Toluca',
        'Toreo',
        'Vía Moreles',
        'Ermita',
        'Coacalco',
        'IESCA',
      ]
      break
    case 'Criminal_stica':
      planteles = [
        'Chapultepec',
        'CD. Azteca',
        'Coacalco',
        'Ermita',
        'Norte',
        'Oriente',
        'Tlalpan',
        'Toreo',
      ]
      break
    case 'Derecho':
      planteles = [
        'Centro',
        'Chalco',
        'CD. Azteca',
        'Cuautitlán',
        'Ermita',
        'Iztapalapa',
        'Norte',
        'León',
        'Oriente',
        'San Ángel',
        'Sur I',
        'Tláhuac',
        'Tlalnepantla',
        'Tlalpan',
        'Toluca',
        'Toreo',
        'Vía Morelos',
        'Coacalco',
        'Chapultepec',
        'IESCA',
      ]
      break
    case 'Dise_o Gr_fico':
      planteles = ['León', 'Norte', 'Tlalnepantla', 'Xola']
      break
    case 'Mercadotecnia':
      planteles = [
        'Centro',
        'CD. Azteca',
        'León',
        'Norte',
        'San Ángel',
        'Tláhuac',
        'Tlalnepantla',
        'Toreo',
        'Vía Morelos',
        'Viaducto',
      ]
      break
    case 'Negocios internacionales':
      planteles = ['Coacalco', 'Tlalnepantla', 'Vía Morelos']
      break
    case 'Pedagog_a':
      planteles = [
        'Chalco',
        'Chapultepec',
        'CD. Azteca',
        'Coacalco',
        'Ermita',
        'Iztapalapa',
        'León',
        'Norte',
        'Oriente',
        'San Ángel',
        'Tláhuac',
        'Tlalnepantla',
        'Toluca',
        'Toreo',
        'Vía Morelos',
        'Xola',
        'Cuautitlán',
      ]
      break
    case 'Publicidad y Medios':
      planteles = ['León', 'Tlalnepantla', 'Norte']
      break
    case 'Relaciones internacionales':
      planteles = ['Centro', 'Chapultepec', 'Tlalpan']
      break
  }

  for (let i = 0; i < planteles.length; i++) {
    arrPlanteles.push({ value: planteles[i], text: planteles[i] })
  }
  arrPlanteles.unshift({
    value: null,
    text: 'Por favor selecciona un plantel',
    disabled: true,
  })

  return arrPlanteles
}

export const states = [
  { value: null, text: 'Selecciona un estado' },
  { value: 'Aguascalientes', text: 'Aguascalientes' },
  { value: 'Baja California', text: 'Baja California' },
  { value: 'Baja California Sur', text: 'Baja California Sur' },
  { value: 'Campeche', text: 'Campeche' },
  { value: 'Coahuila de Zaragoza', text: 'Coahuila de Zaragoza' },
  { value: 'Colima', text: 'Colima' },
  { value: 'Chiapas', text: 'Chiapas' },
  { value: 'Chihuahua	', text: 'Chihuahua	' },
  { value: 'CDMX', text: 'CDMX' },
  { value: 'Durango', text: 'Durango' },
  { value: 'Guanajuato', text: 'Guanajuato' },
  { value: 'Guerrero', text: 'Guerrero' },
  { value: 'Hidalgo', text: 'Hidalgo' },
  { value: 'Jalisco', text: 'Jalisco' },
  { value: 'México', text: 'México' },
  { value: 'Michoacán de Ocampo', text: 'Michoacán de Ocampo' },
  { value: 'Morelos', text: 'Morelos' },
  { value: 'Nayarit', text: 'Nayarit' },
  { value: 'Nuevo León', text: 'Nuevo León' },
  { value: 'Oaxaca', text: 'Oaxaca' },
  { value: 'Puebla', text: 'Puebla' },
  { value: 'Querétaro', text: 'Querétaro' },
  { value: 'Quintana Roo', text: 'Quintana Roo' },
  { value: 'San Luis Potosí', text: 'San Luis Potosí' },
  { value: 'Sinaloa', text: 'Sinaloa' },
  { value: 'Sonora', text: 'Sonora' },
  { value: 'Tabasco', text: 'Tabasco' },
  { value: 'Tamaulipas', text: 'Tamaulipas' },
  { value: 'Tlaxcala', text: 'Tlaxcala' },
  { value: 'Veracruz', text: 'Veracruz' },
  { value: 'Yucatán', text: 'Yucatán' },
  { value: 'Zacatecas', text: 'Zacatecas' },
]

export const careers = [
  'Utel',
  'Kuepa',
  'Universidad tres cultura',
  'Licenciatura en Arquitectura',
  'Licenciatura en Comunicación',
  'Licenciatura en Contabilidad',
  'Licenciatura en Derecho',
  'Licenciatura en Desarrollo Humano y Coaching',
  'Licenciatura en Finanzas',
  'Licenciatura en Ingeniería Industrial',
  'Licenciatura en Ingeniería en Sistemas',
  'Licenciatura en Pedagogía',
  'Licenciatura en Marketing Digital',
  'Ingeniería en Sistemas Computacionales',
  'Ingeniería Industrial',
  'Ingeniería Industrial y Administración',
  'Licenciatura en Administración',
  'Licenciatura en Administración de Negocios',
  'Licenciatura en Administración de Recursos Humanos',
  'Licenciatura en Administración de Tecnologías de Información',
  'Licenciatura en Administración de Ventas',
  'Licenciatura en Administración y Finanzas',
  'Licenciatura en Contaduría Pública',
  'Licenciatura en Contaduría y Finanzas',
  'Licenciatura en Mercadotecnia',
  'Licenciatura en Negocios Internacionales',
  'Licenciatura en Arte Digital y Multimedia',
  'Licenciatura en Ciencias Políticas y Administración Pública',
  'Licenciatura en Comunicación Corporativa',
  'Licenciatura en Comunicación Digital',
  'Licenciatura en Comunicación Organizacional',
  'Licenciatura en Criminología y Criminalística',
  'Licenciatura en Derecho Empresarial',
  'Licenciatura en Derecho Internacional',
  'Licenciatura en Marketing y Publicidad',
  'Licenciatura en Medios Digitales',
  'Licenciatura en Psicología',
  'Licenciatura en Psicología Organizacional',
  'Licenciatura en Administración de Empresas Turísticas',
  'Licenciatura en Desarrollo Sustentable y Ecoturismo',
  'Licenciatura en Administración Financiera',
  'Licenciatura en Administración Pública',
  'Licenciatura en Administración de Empresas',
  'Licenciatura en Administración de Empresas de Entretenimiento y Comunicación',
  'Licenciatura en Administración de Tecnologías de la Información',
  'Licenciatura en Comercio Internacional',
  'Licenciatura en Comunicación y Medios',
  'Licenciatura en Contaduría Pública y Finanzas',
  'Licenciatura en Criminología',
  'Licenciatura en Diseño Digital y Animación',
  'Licenciatura en Diseño Gráfico y Comunicación Visual',
  'Licenciatura en Economía y Finanzas',
  'Licenciatura en Educación',
  'Licenciatura en gestión de Ventas y Comercialización',
  'Licenciatura en Mercadotecnia Digital y Publicidad',
  'Licenciatura en Publicidad y Medios',
  'Licenciatura en Relaciones Internacionales',
  'Licenciatura en Químico Farmacéutico Biólogo',
  'Licenciatura en Cultura Física y Deportes',
  'Licenciatura en Diseño de Modas',
  'Licenciatura en Lenguas Extranjeras',
  'Licenciatura en Medicina',
  'Licenciatura en Economía',
  'Licenciatura en Cirujano Dentista',
  'Licenciatura en Enfermería',
  'Licenciatura en Fisioterapia',
  'Licenciatura en Nutrición',
  'Licenciatura en Diseño Gráfico',
  'Licenciatura en Diseño Industrial',
  'Licenciatura en Diseño, Animación y Arte Digital',
  'Licenciatura en Ciencias de la Comunicación',
  'Licenciatura Internacional en Turismo y Reuniones',
  'Licenciatura en Gastronomía',
  'Licenciatura en Estrategias Financieras y Contables',
  'Licenciatura en Ingeniería en Sistemas Computacionales',
  'Licenciatura en Ingeniería Industrial Administrativa',
  'Licenciatura en Mercadotecnia y Social Media',
  'Licenciatura en Administración de Hoteles y Restaurantes',
  'Licenciatura en Nutrición y Tecnología de los Alimentos',
  'Licenciatura En Mercadotecnia',
  'Licenciatura en Turismo',
  'Licenciatura Contaduría y Finanzas',
  'Licenciatura Administración de Empresas',
  'Licenciatura en Sistemas Computacionales',
  'Licenciatura en Diseño Digital',
  'Ingeniería en Ciencia de Datos',
  'Ingeniería en diseño de software y redes',
  'Ingeniería en innovación',
  'Ingeniería en Logística',
  'Ingeniería en Negocios y Manufactura',
  'Ingeniería en Tecnologías y Sistemas de la información',
  'Ingeniería Industrial y de sistemas',
  'Licenciatura en Administración de Empresas del Entretenimiento',
  'Licenciatura en Administración de Negocios Internacionales',
  'Licenciatura en Comercio y Logística Internacional',
  'Licenciatura en Contaduría Pública y FInanzas',
  'Licenciatura en Dirección de Ventas',
  'Licenciatura en Medicina Veterinaria y zootecnia',
  'Licenciatura en Químico Farmaceútico Biotecnólogo',
  'Licenciatura en Comunicación y Medios Digitales',
  'Licenciatura en Relaciones Públicas',
  'Licenciatura en Diseño Multimedia',
  'Licenciatura en Diseño de la moda e industrial del vestido (NABA)',
  'Licenciatura en Diseño y Comunicación Gráfica',
  'Licenciatura en Administración Turística y Hotelera',
  'Licenciatura en Gastronomía KENDALL',
  'Ingeniería Biomédica',
  'Ingeniería Civil',
  'Ingeniería Mecatrónica',
  'Ingeniería en Petróleo y Gas',
  'Ingeniería en Animación e Interactividad',
  'Ingeniería en Energía y Desarrollo Sostenible',
  'Ingeniería Industrial y de Sistemas',
  'Ingeniería Mecánica Industrial',
  'Ingeniería Mecatrónica con Enfoque Autmotriz',
  'Licenciatura en Administración de Empresas del entretenimiento',
  'Licenciatura en Comercio y logística Internacionales',
  'Licenciatura en Contaduría Pública y finanzas',
  'Licenciatura en Economía y finanzas',
  'Licenciatura en Finanzas y Banca',
  'Licenciatura en Mercadotecnia Deportiva Internacional',
  'Licenciatura en Administración de Negocios de Comunicación y Entretenimiento',
  'Licenciatura en Administración y Liderazgo Empresarial',
  'Licenciatura en Contaduría',
  'Licenciatura en Comercio y Finanzas Internacionales',
  'Licenciatura en Arquitectura de Interiores y Ambientación',
  'Licenciatura en Diseño de Animación',
  'Licenciatura en Diseño de Modas (Próximamente)',
  'Licenciatura en Diseño para la Comunicación en Medios Digitales',
  'Licenciatura en Ingeniería Industrial en Producción',
  'Licenciatura en Médico Cirujano',
  'Licenciatura en Dirección de Hoteles',
  'Licenciatura en Gastronomía y gestión Restaurantera',
  'Licenciatura en Turismo (Nueva)',
  'Licenciatura en Cinematografía',
  'Licenciatura en Comunicación y Manejo de Redes Sociales',
  'Licenciatura en Comunicación y Periodismo',
  'Licenciatura en Comunicación y Relaciones Públicas',
  'Licenciatura en Mercadotecnia (Próximamente)',
  'Licenciatura en Publicidad (Nueva)',
  'Licenciatura en gestión Deportiva',
  'Licenciatura en Administración de Empresas de la Hospitalidad',
  'Licenciatura en Administración del Talento Humano',
  'Licenciatura en Administración Pública y Ciencias Políticas',
  'Licenciatura en Administración y Dirección Estratégica',
  'Licenciatura en Arquitectura de Interiores',
  'Licenciatura en Ciencia de Datos para Negocios',
  'Licenciatura en Ciencias de la Educación',
  'Licenciatura en Ciencias del Deporte',
  'Licenciatura en Comunicación Integrada en las Organizaciones',
  'Licenciatura en Creación e Innovación de empresas',
  'Licenciatura en Criminología, Victimología y Política Criminal',
  'Licenciatura en Desarrollo de Software',
  'Licenciatura en Dirección de Mercadotecnia',
  'Licenciatura en Ecoturismo y Sustentabilidad',
  'Licenciatura en Finanzas y Administración Bancaria',
  'Licenciatura en Historia',
  'Licenciatura en Ingeniería en Sistemas y Tecnologías de la Información',
  'Licenciatura en Ingeniería Industrial y Administrativa',
  'Licenciatura en Lengua y Literatura',
  'Licenciatura en Mercadotecnia Digital y Community Manager',
  'Licenciatura en Mercadotecnia y Publicidad',
  'Licenciatura en Organización y Relaciones Públicas para la Alta Dirección',
  'Licenciatura en Psicopedagogía',
  'Licenciatura en Ventas y Comercialización',
  'TSU en Administración Pública',
  'Licenciatura en Administración de empresas de la hospitalidad',
  'Licenciatura en Comunicación integrada en las organizaciones',
  'Licenciatura en Comercio y Negocios Internacionales',
  'Licenciatura en Adminsitración',
  'licenciatura en Derecho',
  'Licenciatura en Psicología Empresarial',
  'Licencaitura en Administración',
  'Ingeniería en Computación Administrativa',
  'Ingeniería en Mecatrónica',
  'licenciatura en MErcadotecnia',
  'Licenciatura en Creación y Desarrollo de Empresas',
  'Licenciatura en Adminsitración de Empresas',
  'Ingeniería en Desarrollo de Software',
  'Licenciatura en Adminsitración Hotelera y Turística',
  'Licenciatura en Diseño Gráfico y Animación',
  'Licenciatura en Informática Administrativa',
  'Licenciatura en Derecho con acentuación en Economía',
  'Licenciatura en gestión Turística',
  'Ingeniería en Tecnologías Computacionales',
  'Licenciaturas en Ciencias de la Educación',
  'Contador Público',
  'Ingeniería en gestión Empresarial',
  'Licenciatura en Administración FInanciera',
  'Licenciatura en Derecho Coporativo',
  'Licenciatura en Derecho y Finanzas',
  'Licenciatura en Mercadotecnia Turística',
  'Licenciatura en Recursos Humanos',
  'Licenciatura en Producción de Televisión',
  'Lciencaitura en Ciencias de la Educación',
  'licenciatura en Mercadotecnia',
  'Licenciatura en Administración de Negocios de Turismo y Hospitalidad',
  'Licenciatura en Actuaría',
  'Licenciatura en Administración Pública y Gobierno',
  'Licenciatura en Administración Turística',
  'Licenciatura en Administración y Dirección de Empresas',
  'Licenciatura en Artes visuales',
  'Licenciatura en Biotecnología',
  'Licenciatura en Médico Cirujano Dentista',
  'Licenciatura en Dirección de Empresas del Entretenimiento',
  'Licenciatura en Dirección de Restaurantes',
  'Licenciatura en Dirección del Deporte',
  'Licenciatura en Dirección Financiera',
  'Licenciatura en Dirección Internacional de Hoteles',
  'Licenciatura en Diseño de Moda e Innovación',
  'Licenciatura en Finanzas y Contaduría Pública',
  'Licenciatura en Ingeniería Ambiental',
  'Licenciatura en Ingeniería Biomédica',
  'Licenciatura en Ingeniería Civil',
  'Licenciatura en Ingeniería en Sistemas y Tecnología de la Información',
  'Licenciatura en Ingeniería Industrial para la Dirección',
  'Licenciatura en Ingeniería Mecatrónica',
  'Licenciatura en Ingeniería Química',
  'Licenciatura en Inteligencia Estratégica',
  'Licenciatura en Lenguas Modernas y gestión Cultural',
  'Licenciatura en Mercadotecnia Estratégica',
  'Licenciatura en Música Contemporánea',
  'Licenciatura en Pedagogía Organizacional y Educativa',
  'Licenciatura en Responsabilidad Social y Sustentabilidad',
  'Licenciatura en Teatro y Actuación',
  'Licenciatura en Terapia Física y Rehabilitación',
  'Deporte y Bienestar',
  'Ingeniería Online en Transporte y Sistemas de Distribución',
  'Ingeniería Online en Tecnología Ambiental',
  'Ingeniería Online Industrial en Innovación Tecnología',
  'Ingeniería Online en Mecatrónica para la Manufactura',
  'Ingeniería Online en Diseño Mecánico',
  'Ingeniería Online en Diseño Electrónico',
  'Ingeniería Online en Energía',
  'Ingeniería Online en Logística',
  'Dirección y Administración de Instituciones de Salud',
  'Licenciatura Contaduría Pública',
  'Licenciatura Comercio Internacional',
  'Licenciatura Mercadotecnia',
  'Enfermería',
  'Psicología',
  'Nutrición',
  'Licenciatura en Trabajo Social',
  'Diseño Gráfico Digital',
  'Licenciatura en Puericultura',
  'Educación en la Enseñanza de Lenguas Extranjeras',
  'Educación Física y en Deporte',
  'Ingeniería Industrial Automotriz',
  'Ingeniería en Tecnologías de la Información',
  'Licenciatura en Criminalística',
  'Ciencias de la Educación',
  'Pedagogía',
  'Administración de Empresas Turísticas',
  'Administración de empresas',
  'Comercio Internacional',
  'Fisioterapia',
  'Criminalística',
  'Ciencias de la Comunicación',
  'Diseño de Animación Digital',
  'Diseño Arquitectónico y de Interiores',
  'Gastronomía',
  'Licencatura en Administración de Empresas',
  'Optometría',
  'Psicología Clínica',
  'Ingeniería en Redes Computacionales',
  'Ingeniería en Sistemas Computacionales (En línea)',
  'Ingeniería Industrial (En línea)',
  'Licenciatura en Pedagogía (En línea)',
  'Licenciatura en Contaduría (En línea)',
  'Licenciatura en Criminalística (En línea)',
  'Licenciatura en Derecho (En línea)',
  'Licenciatura en Ciencias de la Educación (En línea)',
  'Licencatura en Administración de Empresas (En línea)',
  'Licenciatura en Mercadotecnia (En línea)',
  'Licenciatura en Comercio Internacional (En línea)',
  'Licenciatura en Administración de Empresas Turísticas (En línea)',
  'Licenciatura en Psicología (En línea)',
  'Licenciatura en Mercadotecnia Internacional',
  'Licenciatura en Administración del Tiempo Libre',
  'Licenciatura en Música',
  'Licenciatura en Administración de Empresas y Desarrollo de Negocios Innovadores',
  'Licenciatura en Publicidad y Producción de Contenidos',
  'Licenciatura en Innovación y Administración de Negocios del Entretenimiento',
  'Licenciatura en Diseño y Animacion Digital',
  'Licenciatura en Mercadotecnia y Medios Digitales',
  'Licenciatura en Finanzas y Contaduría',
  'Licenciatura en Actuación',
  'Licenciatura en Cine y Televisión Digital',
  'Licenciatura en Comunicación Multimedia',
  'Licenciatura en Creación y gestión de empresas Turísticas',
  'Licenciatura en Tecnologías de la Información',
  'Ciencias de la Educación con Terminal en Psicología Educativa',
  'Trabajo social',
  'Administración de Empresas',
  'Derecho',
  'Plan estándar con clases grupales',
  'Plan Premium con clases particulares',
  'Licenciatura en Literatura Latinoamericana',
  'Licenciatura en Diseño de Indumentaria y Moda',
  'Ingeniería Física',
  'Licenciatura en Contaduría y gestión Empresarial',
  'Licenciatura en Ciencias Teológicas',
  'Ingeniería Mecánica y Eléctrica',
  'Licenciatura en Filosofía',
  'Licenciatura en Administración de la Hospitalidad',
  'Licenciatura en Ingeniería en Tecnologías de Cómputo y Telecomunicaciones',
  'Licenciatura en Nutrición y Ciencia de los Alimentos',
  'Ingeniería en Mecatrónica y Producción',
  'Licenciatura en Historia del Arte',
  'Licenciatura en Diseño Textil',
  'Licenciatura en Ingeniería de Alimentos',
  'Ingeniería Química',
  'Licenciatura en Desarrollo Comunitario para el Envejecimiento',
  'Licenciatura en Ingeniería Agronómica en Recursos Naturales Renovables',
  'Licenciatura en Nanotecnología',
  'Licenciatura en Estudios Sociales y gestión Local',
  'Licenciatura en Bibliotecnología y Estudios de la Información',
  'Licenciatura en Ciencias Agrogenómicas',
  'Antropología',
  'Licenciatura de Química de Alimentos',
  'Licenciatura de Ingeniería Geolígica',
  'Licenciatura en Investigación Biomédica Básica',
  'Licenciatura en Ciencias Ambientales',
  'Licenciatura de Médico Cirujano',
  'Licenciatura en Lengua y Literaturas Modernas',
  'Licenciatura en Tecnología',
  'Licenciatura de Física',
  'Ingeniería Mecánica',
  'Licenciatura de Ingeniería Química Metalúrgia',
  'Licenciatura de Ingeniería en Computación',
  'Licenciatura en Música-Educación Musical',
]
